version: '3'
services:
    server:
        image: andreterebinto/testapp:latest
        ports:
            - "80:80"
        tty: true
        expose:
            - "80" 
        stdin_open: true
        environment:
            - MODE=dev